### PR TITLE
Replace ts() to E::ts()

### PR DESCRIPTION
**Pull request by lucky091588**

### CODE REVIEW

**Comment by lucky091588** [comment]
Extension already regenerated but I need help on testing this one since I don't know where to test it on the browser.

**Comment by twomice** [comment]
Sorry @lucky091588 As mentioned elsewhere a moment ago, I forgot to explain that we don't want to change files which are PHP overrides of civicrm core files. In this case that includes custom_code/4.6/CRM/Contribute/Form/ContributionPage/Amount.php and  custom_code/4.7/CRM/Contribute/Form/ContributionPage/Amount.php

Please revert changes in those files and update the PR. Thanks.

**Comment by lucky091588** [comment]
@twomice Done reverting the changes on the overwritten core files.

**Comment by twomice** [comment]
Merged, thanks @lucky091588

**Pull request merged**
